version: '3.8'

# 
services:
    rabbitmq:
        image: rabbitmq:3-management
        container_name: rabbitmq
        environment:
          - RABBITMQ_DEFAULT_USER=myuser
          - RABBITMQ_DEFAULT_PASS=mypassword
        ports:
            - 5672:5672
            - 15672:15672
        networks:
          - rabbit_network
        restart: always
    
    app:
      build:
        context: .
        dockerfile: Dockerfile
      ports:
        - "8080:8080"
      networks:
        - rabbit_network
      restart: always


    mongo_db:
      image: mongo:4.2.12
      environment:
        MONGO_INITDB_ROOT_USERNAME: myuser
        MONGO_INITDB_ROOT_PASSWORD: mypassword
      volumes:
        - ../MongoDb/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      ports:
        - "27017:27017"
      networks:
        - rabbit_network


    mongo_express:
      image: mongo-express:0.54.0
      environment:
        - ME_CONFIG_OPTIONS_EDITORTHEME=default
        - ME_CONFIG_MONGODB_SERVER=mongo_db
        - ME_CONFIG_MONGODB_PORT=27017
        - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
        - ME_CONFIG_MONGODB_AUTH_DATABASE=mydb
        - ME_CONFIG_MONGODB_ADMINUSERNAME=myuser
        - ME_CONFIG_MONGODB_ADMINPASSWORD=mypassword
      ports:
        - "8083:8081"
      restart: on-failure
      depends_on:
        - mongo_db
      networks:
        - rabbit_network
    

networks:
  rabbit_network:
    driver: bridge
        

    